---
name: practical-04
break: true
indent: 4
---
src/main:
    java:
        coins/MinCoins.java:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
            MatchFileFragment --fragment "int quarters" --count 1 --exact
            MatchFileFragment --fragment "int dimes" --count 1 --exact
            MatchFileFragment --fragment "int nickels" --count 1 --exact
            MatchFileFragment --fragment "int pennies" --count 1 --exact
            MatchFileFragment --fragment "+=" --count 2
            MatchFileFragment --fragment "\"-=\"" --count 2
            MatchFileFragment --fragment "\t" --count 4
        
CountCommits --count 2
ExecuteCommand --command "gradle build"
MatchCommandRegex --command "gradle run --args='1.23'" --regex "5" --count 1
